# Generated by Django 4.2.7 on 2023-11-05 17:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('CarID', models.AutoField(primary_key=True, serialize=False)),
                ('CarBrand', models.CharField(choices=[('fiesta', 'Fiesta'), ('focus', 'Focus'), ('fusion', 'Fusion'), ('mondeo', 'Mondeo')], max_length=7)),
                ('NewCarPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('ClientCode', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255)),
                ('BankAccount', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=15)),
                ('ContactPerson', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Repairs',
            fields=[
                ('RepairCode', models.AutoField(primary_key=True, serialize=False)),
                ('RepairStartDate', models.DateField()),
                ('RepairType', models.CharField(choices=[('гарантійний', 'Гарантійний'), ('плановий', 'Плановий'), ('капітальний', 'Капітальний')], max_length=15)),
                ('HourlyRepairCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('HoursRequired', models.PositiveSmallIntegerField()),
                ('CarCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.cars')),
            ],
        ),
        migrations.AddField(
            model_name='cars',
            name='ClientCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp1.clients'),
        ),
    ]
